# Running hooks on commit (pre-commit) and push (pre-push)
default_stages: [pre-commit, pre-push]
repos:
    # Standard hooks for cleaning files
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: check-json

    # Ruff
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
    -   id: ruff
        name: Ruff Lint (Autofix)
        args: ["--fix", "--exit-zero"] 
    -   id: ruff-format
        name: Ruff Format


    # Mypy
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.8.0'
    hooks:
    -   id: mypy
        name: Mypy Type Check
        args: ["--config=pyproject.toml", "--no-incremental"]
